# Header
menu:
  Home: /
  # Archives: /archives
  # About: /about
  Weibo: http://www.weibo.com/p/1005051896403155
  Github: https://github.com/shenqihui
  Mail: mailto:c2hlbnFpaHVpMDkyMEBnbWFpbC5jb20K

rss: /atom.xml

menu_icon:
  Home: fa-home
  Archives: fa-archive
  About: fa-user
  Weibo: fa-weibo
  Github: fa-github
  Mail: fa-envelope-o

# Content
excerpt_link: Read More
fancybox: true

#your personal image
your_img: /img/profile_img.jpg

# Miscellaneous
google_analytics: UA-48454013-1
baidu_analytics: a359010dd82707c1ee6d1ca5d64be33b
favicon: /favicon.ico
twitter: shenqihui
google_plus: 
fb_admins:
fb_app_id:

footerword: “我们俩都是年轻人，要将自己献身于伟大事业的开创，我们是天生的魔术师，但我们不会用自己的天赋去伤害任何人。” -- 阿尔弗雷德·波登 《致命魔术》
